apiVersion: v1
kind: Pod
metadata: 
  name: pod-klever
  labels:
    app: pod-klever
spec:
  containers: 
    - name: pod-klever
      image: matheusmorozetti/klever
      ports: 
        - containerPort: 80
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 15
